import json
import uuid
import re
from typing import Dict, Optional, List, Tuple
from app.core.logging_utils import log_info, log_error, log_warning
from app.core_logic.template_manager.template_manager import TemplateManager
from app.services.action_logger import ActionLogger
from .visual_mapper import VisualMapperMixin
from .page_builder import PageBuilderMixin

class ReportGenerator(VisualMapperMixin, PageBuilderMixin):
    def __init__(self, file_agent, action_logger: Optional[ActionLogger] = None):
        self.file_agent = file_agent
        self.template_manager = TemplateManager()
        self.action_logger = action_logger or ActionLogger()
        self.skipped_visuals = []

    async def generate_and_push_report(
        self,
        destination_folder: str,
        app_name: str,
        report_data: Optional[Dict] = None,
        repo: Optional[str] = None,
        org: Optional[str] = None,
        project: Optional[str] = None,
        token: Optional[str] = None,
    ) -> bool:
        self.skipped_visuals = []
        files_to_push = []
        log_info(f"Generating static project files for: {app_name}")

        # Get context from logging_utils
        from app.core.logging_utils import _project_id_ctx, _workbook_id_ctx, _run_id_ctx, get_log_token
        p_id = _project_id_ctx.get()
        w_id = _workbook_id_ctx.get()
        r_id = _run_id_ctx.get()
        log_token = get_log_token()

        await self.action_logger.send_activity_to_api(
            p_id, w_id, r_id, 
            technical_message=f"Starting report generation for: {app_name}",
            token=log_token
        )

        report_id = str(uuid.uuid4())
        model_id = str(uuid.uuid4())

        replacements = {
            "app_name": app_name,
            "report_logical_id": report_id,
            "model_logical_id": model_id
        }

        static_files_map = {
            f"{app_name}.Report/definition.pbir": "definition.pbir.json",
            f"{app_name}.Report/.platform": "report_platform.json",
            f"{app_name}.Report/.pbi/localSettings.json": "report_localSettings.json",
            f"{app_name}.SemanticModel/definition.pbism": "definition.pbism.json",
            f"{app_name}.SemanticModel/.platform": "semantic_platform.json",
            f"{app_name}.SemanticModel/.pbi/localSettings.json": "semantic_localSettings.json",
            f"{app_name}.SemanticModel/.pbi/editorSettings.json": "editorSettings.json",
            f"{app_name}.SemanticModel/diagramLayout.json": "diagramLayout.json",
            f"{app_name}.Report/StaticResources/SharedResources/BaseThemes/CY24SU10.json": "CY24SU10.json"
        }

        for dest_path, template_file in static_files_map.items():
            full_dest = f"{destination_folder}/{dest_path.format(app_name=app_name)}"
            content_str = self.template_manager.load_and_replace_template("static", template_file, replacements)
            files_to_push.append((full_dest, content_str, "add"))

        files_to_push.append((f"{destination_folder}/readme", f"Project: {app_name}\nGenerated by Migration Agent", "add"))

        if report_data:
            report_files = await self._generate_dynamic_visuals(report_data, app_name)
            for rel_path, file_content in report_files:
                full_dest = f"{destination_folder}/{app_name}.Report/definition/{rel_path}"
                files_to_push.append((full_dest, file_content, "add"))
                log_info(f"Generated report file: {rel_path}")

        if not files_to_push:
            log_error("No files prepared for push")
            return False

        success = await self.file_agent.batch_update_files(
            files_to_push,
            repo=repo,
            org=org,
            project=project,
            token=token,
        )
        if success:
            log_info(f"Pushed {len(files_to_push)} generated files successfully")
            await self.action_logger.send_activity_to_api(
                p_id, w_id, r_id, 
                technical_message=f"Successfully pushed {len(files_to_push)} report files to repository",
                token=log_token
            )
        else:
            await self.action_logger.send_error_to_api(
                p_id, w_id, r_id, 
                technical_message="Failed to push report files to repository",
                token=log_token
            )
        return success

